### ISSUE TITLE
Escape characters in labels

### ISSUE THREAD

**Issue by fregante** [refined-github/shorten-repo-url#19]
Live URL: https://github.com/sindresorhus/refined-github/labels/Please%21%20%E2%99%A5

It could be [sindresorhus/refined-github/Please ♥ (label)](https://github.com/sindresorhus/refined-github/labels/Please%21%20%E2%99%A5)

**Comment by yakov116** [comment]
https://github.com/fregante/shorten-repo-url/commit/9cddb988a9fabc12b65a225e0806f09579ec60e2

Broke the link, it needs to be unencoded in the search

**Comment by fregante** [comment]
D'oh!

**Comment by fregante** [comment]
I'll fix it

**Comment by fregante** [comment]
I'm confused, shorten-repo-url doesn't touch the URL. I think this is an issue in RGH 🤔

**Comment by fregante** [comment]
Indeed, it's not a RG issue but a GitHub issue. Try disabling RG

**Comment by yakov116** [comment]
Wow! 👍

**Comment by fregante** [comment]
I see what happened. GitHub just changed their escaping

The URL used to be

```
https://github.com/sindresorhus/refined-github/labels/Please%21%20♥
```

and now it's

```
https://github.com/sindresorhus/refined-github/labels/Please%21%20♥%EF%B8%8E
```

**Comment by fregante** [comment]
ChatGPT

> %EF%B8%8E: This is the URL-encoded representation of the UTF-8 encoding for the variation selector-16 (U+FE0E). This is used to indicate that the preceding emoji (in this case, the heart "♥") should be displayed as a text-style emoji rather than a graphical emoji.
