### ISSUE TITLE
Drop shortening of compare links?

### ISSUE THREAD

**Issue by cheap-glitch** [refined-github/shorten-repo-url#37]
All the following links are now natively shortened:

```
- https://github.com/refined-github/shorten-repo-url/compare/use-named-groups...main
- https://github.com/refined-github/shorten-repo-url/compare/v2.3.0...main
- https://github.com/refined-github/shorten-repo-url/compare/v2.1.1...v2.3.0
- https://github.com/refined-github/shorten-repo-url/compare/56db9af54a2ffb7ffaa7d622ce57414f8b25cfae...a7c81316f438c38ce71b13309b974f0eb8c6838a
- https://github.com/refined-github/refined-github/compare/22.3.3...main
```

- https://github.com/refined-github/shorten-repo-url/compare/use-named-groups...main
- https://github.com/refined-github/shorten-repo-url/compare/v2.3.0...main
- https://github.com/refined-github/shorten-repo-url/compare/v2.1.1...v2.3.0
- https://github.com/refined-github/shorten-repo-url/compare/56db9af54a2ffb7ffaa7d622ce57414f8b25cfae...a7c81316f438c38ce71b13309b974f0eb8c6838a
- https://github.com/refined-github/refined-github/compare/22.3.3...main

That said, I've noticed a bug where compare links with a hash will become broken:
```
https://github.com/refined-github/shorten-repo-url/compare/use-named-groups...main#diff
```

https://github.com/refined-github/shorten-repo-url/compare/use-named-groups...main#diff

So maybe we can do something about that. (Or we just wait until GitHub fixes it).

**Comment by fregante** [comment]
Yes that's another GitHub that always existed, even for PR commit links with hashes I think. 

As for this request, if we see this module as a filler of missing GitHub abbreviations, then we should drop it. If it's a generic reusable shortener, we shouldn't. 

Unfortunately for the latter we already lack support for regular issues and PRs and nobody every asked for it, sooooooo… let's drop it?

**Comment by fregante** [comment]
No harm in leaving it
