### ISSUE TITLE
vitest does not catch invalid cases

### ISSUE THREAD

**Issue by scarf005** [refined-github/shorten-repo-url#59]
after #58, vitest will not catch invalid cases such as:

![image](https://github.com/user-attachments/assets/36ccc40e-72e6-4706-86cf-dd7a79616801)

this is likely due to using deprecated API with incompatible function.

![image](https://github.com/user-attachments/assets/2aa00d6c-879f-43d8-94f4-a445a90db28a)

**Comment by fregante** [comment]
Indeed I merged the PR too early. I fixed it in https://github.com/refined-github/shorten-repo-url/commit/7c05f2c24eda58c4b87ea88e58b3ae1ed1be3073
